apiVersion: v2
name: lvm-localpv
description: CSI Driver for dynamic provisioning of LVM Persistent Local Volumes.
version: 1.0.2
appVersion: 1.0.0
icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/openebs/icon/color/openebs-icon-color.png
home: http://www.openebs.io/
keywords:
  - cloud-native-storage
  - block-storage
  - filesystem
  - LVM
  - Local Persistent Volumes
  - storage
sources:
- https://github.com/openebs/lvm-localpv
maintainers:
  - name: prateekpandey14
    email: prateek.pandey@mayadata.io
  - name: pawanpraka1
    email: pawan@mayadata.io
  - name: iyashu
    email: yashpal.c1995@gmail.com
